name: 'Elasti APM Sourcemap Uploader'
description: 'Upload sourcemaps in a folder to Elastic APM'
inputs:
  jsfolder:
    description: 'Location of generated JS'
    required: true
  server-path:
    description: 'Server Path'
    required: true
  service-version:
    description: 'Version String'
    required: true
  service-name:
    description: 'Service Name in APM'
    required: true
  apm-server:
    description: 'URL for the APM server'
    required: true
  apm-token:
    description: 'Access token for the APM server'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
